repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.2.2'
    hooks:
      - id: poetry-export
      - id: poetry-export
        args : ["-f", "requirements.txt", "-o", "requirements-dev.txt", "--with", "dev"]