# This is a basic workflow to help you get started with the Pull request comment action.

name: Exemple

# Controls when the workflow will run
# This workflow does only support running on PR. 
on:
  pull_request:
    branches: [ "main", "devlopement" ]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Add a comment to the PR
        uses: Correlatio-company/Pull-Request-Comments@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          filename: template.md

